container:
  image: cirrusci/android-sdk:18
  cpu: 8
  memory: 20G

test_task:
  create_device_script:
    - sdkmanager "system-images;android-18;default;armeabi-v7a"
    - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  start_emulator_script:
    - $ANDROID_HOME/emulator/emulator -avd test -noaudio -no-window -gpu off -verbose
  wait_for_emulator_script:
    - adb wait-for-device
    - adb shell input keyevent 82
  test_script: ./gradlew clean assemble assembleAndroidTest --stacktrace