container:
  image: cirrusci/android-sdk:18

test_task:
  emulator_script:
    - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -noaudio -no-window -gpu off -verbose -qemu -usbdevice tablet -vnc :0
  wait_for_emulator_script:
    - adb wait-for-device
    - adb shell input keyevent 82
  test_script: ./gradlew clean assemble assembleAndroidTest --stacktrace