container:
  image: bitriseio/docker-android:latest

test_task:
  before_install_script:
    - sdkmanager "system-images;android-18;default;armeabi-v7a"
    # Create and start emulator for the script. Meant to race the install task.
    - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  before_test_script:
    - android-wait-for-emulator
    - adb shell input keyevent 82
  test_script: ./gradlew clean assemble assembleAndroidTest --stacktrace