container:
  image: runmymind/docker-android-sdk:ubuntu-standalone

test_task:
  before_install_script:
    # Install SDK license so Android Gradle plugin can install deps.
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    - sdkmanager tools
    # Install the system image
    - sdkmanager "system-images;android-18;default;armeabi-v7a"
    # Create and start emulator for the script. Meant to race the install task.
    - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  before_test_script:
    - android-wait-for-emulator
    - adb shell input keyevent 82
  test_script: ./gradlew clean assemble assembleAndroidTest --stacktrace