container:
  image: cirrusci/android-sdk:18
  cpu: 4
  memory: 10G

check_task:
  printenv_script: printenv
  emulator_script:
    # Install SDK license so Android Gradle plugin can install deps.
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    # Install the rest of tools (e.g., avdmanager)
    - sdkmanager tools
    # Install the system image
    - sdkmanager "system-images;android-18;default;armeabi-v7a"
    # Create and start emulator for the script. Meant to race the install task.
    - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
  gradle_cache:
    folder: ~/.gradle/caches
  wait_for_emulator_script:
    - adb wait-for-device
    - adb shell input keyevent 82
  check_script: ./gradlew clean assemble assembleAndroidTest check connectedCheck --stacktrace
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete